spring:
  session:
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: provlegisto
    password: secret
    url: jdbc:mysql://127.0.0.1:3306/provlegisto

server:
  port: 80